Fix trajectory preview script
telematics-lab/IoD_Sim pull request #1
Opened 2022-04-15 10:12 UTC by dpugliese6

2022-04-15 10:41 UTC, GiovanniGrieco requested changes

2022-04-15 10:41 UTC, GiovanniGrieco commented on analysis/preview.py
> +        plt.savefig(re.sub('.json','.pdf',args.input_file))
It's better to use [`str.replace()`](https://docs.python.org/3/library/stdtypes.html#str.replace) instead of `re`.

2022-04-15 10:41 UTC, GiovanniGrieco commented on analysis/preview.py
> +    i=0
[`enumerate()`](https://docs.python.org/3/library/functions.html?highlight=enumerate#enumerate) allows to make the for loop cleaner, without the outside `i` index variable

2022-04-15 10:41 UTC, GiovanniGrieco commented on analysis/preview.py
> +            zsp_positions.append(Point(zsp['mobilityModel']['attributes'][0]['value'])) #Actually ZSPs mobilityModel contains always only one attributes (Position)
This assumption is too dangerous for future cases. It would be better to search for `position` attribute and then retrieve its value.

2022-04-15 18:02 UTC, dpugliese6 reviewed
tasks.json
I think in this way usability is improved
install-dependecies.sh
Unlimited support?

2022-04-19 09:10 UTC, GiovanniGrieco approved these changes

2022-04-19 09:14 UTC, GiovanniGrieco commented
I have reverted (and refactored a little bit) `install-dependencies.sh` for the following reason: `apt` and `dnf` do not give us any guarantee on the correct naming of packages in a certain distro. Therefore, the script can break if it is executed on a distro with apt/dnf but do not have a certain package.

2022-04-19 09:16 UTC, merged